db:
  dbms: 'mysql'

sqlite:
  path: '../db/weather.db'

duckdb:
  path: 'db/weather.duckdb'

mysql:
  host: 'mysql'
  user: 'weather'
  password: 'sunny-lime'
  database: 'weather'

provider:
  name: 'tomorrow.io'

location:
  name: 'home'

mqtt:
  broker: 'mq.regul8or.home'
  topic: 'regul8or.home/weather'

ssl:
  ca: '/usr/local/share/ca-certificates/regul8or-home-ca-x1-chain.crt'
