pools:
  - id: Supermicro-6019
    hosts: [ 172.18.0.25, 172.18.0.26, 172.18.0.27, 172.18.0.28 ]
    scope: [ 'metadata', 'host' ]
  - id: srv-sm-x7dcli-1
    hosts: [ 172.18.0.29 ]
    scope: [ 'metadata', 'host' ]

env:
  backup-path: 'c:\temp'
  log-path: 'c:\temp\log'
  pool-metadata-template: '{pool_name}.xml'
  vdi-template: '{vm_name} - {device}.vhd'
  vm-metadata-template: '{vm_name}.tar'
  vm-template: '{vm_name}.xva'

vm:
  - vm-uuid: '94a33466-b76e-b2f4-c4e7-a484f983caf0'
    vm-name: '1C Web Server 3'

vdi:
#  - vm-uuid: '2882af51-704a-c967-a816-7c60443d9a0c'
#    vm-name: 'Backup Server'
#    device: 'xvda'

xe:
  pool-dump-database: 'xe -s {host} -u {username} -pw {password} pool-dump-database file-name="{filename}"'
  vdi-export: 'xe -s {host} -u {username} -pw {password} vdi-export uuid={uuid} format=vhd filename="{filename}"'
  vm-export: 'xe -s {host} -u {username} -pw {password} vm-export uuid={uuid} metadata={metadata} filename="{filename}"'

after:
  metadata:
    - 'echo "After pool metadata backup"'
  vm:
    - 'echo "After each VM backup"'
  vdi:
    - 'echo "After each VDI backup"'
  host:
    - 'echo "After each host backup"'
  job:
    - 'echo After the backup job'
    - 'echo {y:04}-{m:02}-{d:02}'
