pools:
  - id: Supermicro-6019
    hosts: [ 172.18.0.25, 172.18.0.26, 172.18.0.27, 172.18.0.28 ]
    scope: [ 'metadata', 'vm', 'vdi' ]
  - id: srv-sm-x7dcli-1
    hosts: [ 172.18.0.29 ]
    scope: [ 'metadata', 'vm', 'vdi' ]

env:
  backup_location: 'c:\temp'
  log-path: 'c:\temp\log'

vm:
  - vm-uuid: '2e3180e9-02b2-a754-2158-f9966ac56271'
    vm-name: 'Transmission'

xe:
  pool-dump-database: 'xe -s {host} -u {username} -pw {password} pool-dump-database file-name={filename}'

after:
  metadata:
    - 'del {filename}'
