pools:
  - id: Home
    hosts: [ 172.18.0.25, 172.18.0.26, 172.18.0.27, 172.18.0.28 ]
    scope: [ 'metadata', 'vm' ]

env:
  backup_location: 'c:\temp'

xe:
  'pool-dump-database': 'xe -s {host} -u {username} -pw {password} pool-dump-database file-name={filename}'

after:
  metadata:
    - 'del {filename}'
